dist: xenial

language: node_js

node_js: "10"

sudo: false

branches:
  only:
  - develop

cache:
  directories:
    - node_modules

before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin

install:
  - npm install

script:
  # The env variables are set in travis config panel
  - printf '%s\n' "FB_APIKEY=$FB_APIKEY" "FB_AUTHDOMAIN=${FB_AUTHDOMAIN}" "FB_DATABASEURL=$FB_DATABASEURL" "FB_PROJECTID=${FB_PROJECTID}" "FB_STORAGEBUCKET=$FB_STORAGEBUCKET" "FB_MESSAGINGSENDERID=${FB_MESSAGINGSENDERID}" >.env
  - npm run build 
  # runs npm test( or anything ) for regular build and run the provision script if it is a pull request
  - export PATH=$PATH:$HOME/.local/bin
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && npm test || sh ./vagrant/travis.provision.sh ${TRAVIS_PULL_REQUEST}'

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  local-dir: dist
  on:
    branch: develop

notifications:
  slack:
    rooms:
      - secure: pcCmO1feClqyOqhLXZ9Np4rxUQlCRzzp+ltTbHrcD+nne56bO1SWa/zboD7u+ghHDTvxygFRGbdKYMB9RLu8oPUb2fOgzvIErSLt1hTbwQvF073j7a/PBpv3tTcs6fdRokVpghXdU3BzV9E5QbBxf5ngHcS2cc56nSE0cbbjDZ0E6zg5C+S/D06EumVzpRXd05EvGV6L8BrsNwtGIKVGD3mVgflr2HD02G0XbXDBb/G/MdzolA/7Hg1NA/VBazwgfa/NQC+cE9COWsotTeEapg+oigW0AsMu290D0iONa0TkVDoLQX+cTtYhUJVm/8BfebxGZBgTC0x5xi7kR5wvbCzRV6uvGbh4f8lbgxxzDgwoupUSSiY3Joe2KvbmF45yvS5au9VzFlRPUxarLpdrxjY/jm1CF1EX0ohrCr08Gb5U06IG77ltjgXxUgyy/YRedGkzIETOfRQMIJ8/1k2PPLPmGy+el8PBriF1PT/uMQy8A3atQR1qqNn4r2mdZ2PqLYCGdlu9dd5a30etmOBTHZ3hdqH9UonVddAwM2WUkmiLh6yGisQkLAaGKQdDXFcnlq4h7stD2Z+cDbtyhRJFsuasbnhxHlNs/YYWK38nWpq6ZekzAkps3bb4Vl3YhJ8diD+fyxwItcw11A3HlWIPaGNKs3tRZaxNZDoLLbMIUHM=
    template:
      - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository_slug}@%{branch} by %{author} %{result} in %{duration}"
      - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository_slug}@%{branch} in PR <%{pull_request_url}|#%{pull_request_number}> by %{author} %{result} in %{duration}. Pull request deploy: http://yakchat-%{pull_request_number}.s3-website-us-west-1.amazonaws.com"
    on_success: always
    on_failure: always 
