language: node_js
node_js:
  - "8"
dist: trusty
sudo: false

branches:
  only:
  - develop

cache:
  directories:
    - node_modules

install:
  - npm install -g parcel-bundler
  - npm install npm-run-all

script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: 13a05669aff46ad3ebf3eed3fcc871117eae370f
  local_dir: dist
  on:
    branch: develop