dist: xenial

language: node_js

node_js: "10"

sudo: false

branches:
  only:
  - develop

cache:
  directories:
    - node_modules

before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin

install:
  - npm install

script:
  # The env variables are set in travis config panel
  - printf '%s\n' "FB_APIKEY=$FB_APIKEY" "FB_AUTHDOMAIN=${FB_AUTHDOMAIN}" "FB_DATABASEURL=$FB_DATABASEURL" "FB_PROJECTID=${FB_PROJECTID}" "FB_STORAGEBUCKET=$FB_STORAGEBUCKET" "FB_MESSAGINGSENDERID=${FB_MESSAGINGSENDERID}" >.env
  - npm run build 
  # runs npm test( or anything ) for regular build and run the provision script if it is a pull request
  - export PATH=$PATH:$HOME/.local/bin
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && npm test || sh ./vagrant/travis.provision.sh ${TRAVIS_PULL_REQUEST}'

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  local-dir: dist
  on:
    branch: develop

# NOTE: AWS credententials are already set in travis panel as $AWS_ACCESS_KEY_ID and $AWS_SECRET_ACCESS_KEY
# NOTE: TRAVIS_PULL_REQUEST have the pull request number otherwise will be false
# NOTE: TRAVIS_BRANCH could be usefully